package com.hmvsoluciones.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAllPropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertCategoriaProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAllUpdatablePropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertCategoriaProductoUpdatableFieldsEquals(expected, actual);
        assertCategoriaProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoAutoGeneratedPropertiesEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertThat(actual)
            .as("Verify CategoriaProducto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoUpdatableFieldsEquals(CategoriaProducto expected, CategoriaProducto actual) {
        assertThat(actual)
            .as("Verify CategoriaProducto relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaProductoUpdatableRelationshipsEquals(CategoriaProducto expected, CategoriaProducto actual) {
        // empty method
    }
}
